export const seedUsers = [
  {
    fullName: 'Admin User',
    email: 'admin@worknest.demo',
    role: 'admin',
  },
  {
    fullName: 'Demo User One',
    email: 'user1@worknest.demo',
    role: 'user',
  },
  {
    fullName: 'Demo User Two',
    email: 'user2@worknest.demo',
    role: 'user',
  },
];

export const seedBranches = [
  {
    name: 'WorkNest Tel Aviv',
    city: 'Tel Aviv',
    address: 'Rothschild Boulevard 22, Tel Aviv',
    imageUrl: '/images/branches/worknest-tel-aviv.png',
    rating: 5,
    facilities: ['wifi', 'coffee', 'printer', 'kitchen', 'parking', 'accessibility'],
    isActive: true,
  },
  {
    name: 'WorkNest Herzliya',
    city: 'Herzliya',
    address: 'Abba Eban Boulevard 12, Herzliya',
    imageUrl: '/images/branches/worknest-herzliya.png',
    rating: 4,
    facilities: ['wifi', 'coffee', 'printer', 'parking', 'bikeStorage', 'accessibility'],
    isActive: true,
  },
  {
    name: 'WorkNest Jerusalem',
    city: 'Jerusalem',
    address: 'Jaffa Road 89, Jerusalem',
    imageUrl: '/images/branches/worknest-jerusalem.png',
    rating: 4,
    facilities: ['wifi', 'coffee', 'kitchen', 'accessibility'],
    isActive: true,
  },
  {
    name: 'WorkNest Haifa',
    city: 'Haifa',
    address: 'Hanassi Boulevard 45, Haifa',
    imageUrl: '/images/branches/worknest-haifa.png',
    rating: 3,
    facilities: ['wifi', 'coffee', 'printer', 'petFriendly', 'accessibility'],
    isActive: true,
  },
  {
    name: "WorkNest Be'er Sheva",
    city: "Be'er Sheva",
    address: "Rager Boulevard 41, Be'er Sheva",
    imageUrl: '/images/branches/worknest-beer-sheva.png',
    rating: 4,
    facilities: ['wifi', 'coffee', 'parking', 'bikeStorage', 'accessibility'],
    isActive: true,
  },
];

export const workspaceTemplatesByBranch = {
  'WorkNest Tel Aviv': [
    {
      name: 'Office A',
      type: 'office',
      capacity: 2,
      pricePerDay: 220,
      imageUrl: '/images/workspaces/workspace-office.png',
      description: 'A private office for focused work or a small team.',
      equipment: [],
      isActive: true,
    },
    {
      name: 'Small Meeting Room A',
      type: 'smallMeetingRoom',
      capacity: 4,
      pricePerDay: 350,
      imageUrl: '/images/workspaces/workspace-small-meeting-room-a.png',
      description: 'A compact meeting room for interviews, client calls, and team syncs.',
      equipment: ['largeTv'],
      isActive: true,
    },
    {
      name: 'Small Meeting Room B',
      type: 'smallMeetingRoom',
      capacity: 6,
      pricePerDay: 420,
      imageUrl: '/images/workspaces/workspace-small-meeting-room-b.png',
      description: 'A practical meeting room for small presentations and focused team discussions.',
      equipment: ['projector'],
      isActive: true,
    },
    {
      name: 'Large Meeting Room A',
      type: 'largeMeetingRoom',
      capacity: 12,
      pricePerDay: 750,
      imageUrl: '/images/workspaces/workspace-large-meeting-room.png',
      description: 'A larger meeting room for workshops, presentations, and team sessions.',
      equipment: ['largeTv', 'projector'],
      isActive: true,
    },
    {
      name: 'Managed Suite A',
      type: 'managedSuite',
      capacity: 25,
      pricePerDay: 1600,
      imageUrl: '/images/workspaces/workspace-managed-suite.png',
      description: 'A private suite for a larger team, combining work areas and meeting space.',
      equipment: ['largeTv', 'projector'],
      isActive: true,
    },
  ],
  'WorkNest Herzliya': [
    {
      name: 'Office A',
      type: 'office',
      capacity: 2,
      pricePerDay: 220,
      imageUrl: '/images/workspaces/workspace-office.png',
      description: 'A private office for focused work or a small team.',
      equipment: [],
      isActive: true,
    },
    {
      name: 'Office B',
      type: 'office',
      capacity: 4,
      pricePerDay: 260,
      imageUrl: '/images/workspaces/workspace-office.png',
      description: 'A private office for focused work or a small team.',
      equipment: [],
      isActive: true,
    },
    {
      name: 'Small Meeting Room A',
      type: 'smallMeetingRoom',
      capacity: 4,
      pricePerDay: 350,
      imageUrl: '/images/workspaces/workspace-small-meeting-room-a.png',
      description: 'A compact meeting room for interviews, client calls, and team syncs.',
      equipment: ['largeTv'],
      isActive: true,
    },
    {
      name: 'Large Meeting Room A',
      type: 'largeMeetingRoom',
      capacity: 12,
      pricePerDay: 750,
      imageUrl: '/images/workspaces/workspace-large-meeting-room.png',
      description: 'A larger meeting room for workshops, presentations, and team sessions.',
      equipment: ['largeTv', 'projector'],
      isActive: true,
    },
    {
      name: 'Managed Suite A',
      type: 'managedSuite',
      capacity: 25,
      pricePerDay: 1600,
      imageUrl: '/images/workspaces/workspace-managed-suite.png',
      description: 'A private suite for a larger team, combining work areas and meeting space.',
      equipment: ['largeTv', 'projector'],
      isActive: true,
    },
  ],
  'WorkNest Jerusalem': [
    {
      name: 'Office A',
      type: 'office',
      capacity: 2,
      pricePerDay: 220,
      imageUrl: '/images/workspaces/workspace-office.png',
      description: 'A private office for focused work or a small team.',
      equipment: [],
      isActive: true,
    },
    {
      name: 'Small Meeting Room A',
      type: 'smallMeetingRoom',
      capacity: 4,
      pricePerDay: 350,
      imageUrl: '/images/workspaces/workspace-small-meeting-room-a.png',
      description: 'A compact meeting room for interviews, client calls, and team syncs.',
      equipment: ['largeTv'],
      isActive: true,
    },
    {
      name: 'Large Meeting Room A',
      type: 'largeMeetingRoom',
      capacity: 12,
      pricePerDay: 750,
      imageUrl: '/images/workspaces/workspace-large-meeting-room.png',
      description: 'A larger meeting room for workshops, presentations, and team sessions.',
      equipment: ['largeTv', 'projector'],
      isActive: true,
    },
    {
      name: 'Large Meeting Room B',
      type: 'largeMeetingRoom',
      capacity: 10,
      pricePerDay: 700,
      imageUrl: '/images/workspaces/workspace-large-meeting-room.png',
      description: 'A larger meeting room for workshops, presentations, and team sessions.',
      equipment: ['projector'],
      isActive: true,
    },
    {
      name: 'Managed Suite A',
      type: 'managedSuite',
      capacity: 25,
      pricePerDay: 1600,
      imageUrl: '/images/workspaces/workspace-managed-suite.png',
      description: 'A private suite for a larger team, combining work areas and meeting space.',
      equipment: ['largeTv', 'projector'],
      isActive: true,
    },
  ],
  'WorkNest Haifa': [
    {
      name: 'Office A',
      type: 'office',
      capacity: 2,
      pricePerDay: 220,
      imageUrl: '/images/workspaces/workspace-office.png',
      description: 'A private office for focused work or a small team.',
      equipment: [],
      isActive: true,
    },
    {
      name: 'Office B',
      type: 'office',
      capacity: 4,
      pricePerDay: 260,
      imageUrl: '/images/workspaces/workspace-office.png',
      description: 'A private office for focused work or a small team.',
      equipment: [],
      isActive: true,
    },
    {
      name: 'Small Meeting Room A',
      type: 'smallMeetingRoom',
      capacity: 4,
      pricePerDay: 350,
      imageUrl: '/images/workspaces/workspace-small-meeting-room-a.png',
      description: 'A compact meeting room for interviews, client calls, and team syncs.',
      equipment: ['largeTv'],
      isActive: true,
    },
    {
      name: 'Small Meeting Room B',
      type: 'smallMeetingRoom',
      capacity: 6,
      pricePerDay: 420,
      imageUrl: '/images/workspaces/workspace-small-meeting-room-b.png',
      description: 'A practical meeting room for small presentations and focused team discussions.',
      equipment: ['projector'],
      isActive: true,
    },
    {
      name: 'Large Meeting Room A',
      type: 'largeMeetingRoom',
      capacity: 12,
      pricePerDay: 750,
      imageUrl: '/images/workspaces/workspace-large-meeting-room.png',
      description: 'A larger meeting room for workshops, presentations, and team sessions.',
      equipment: ['largeTv', 'projector'],
      isActive: true,
    },
  ],
  "WorkNest Be'er Sheva": [
    {
      name: 'Office A',
      type: 'office',
      capacity: 2,
      pricePerDay: 220,
      imageUrl: '/images/workspaces/workspace-office.png',
      description: 'A private office for focused work or a small team.',
      equipment: [],
      isActive: true,
    },
    {
      name: 'Small Meeting Room A',
      type: 'smallMeetingRoom',
      capacity: 4,
      pricePerDay: 350,
      imageUrl: '/images/workspaces/workspace-small-meeting-room-a.png',
      description: 'A compact meeting room for interviews, client calls, and team syncs.',
      equipment: ['largeTv'],
      isActive: true,
    },
    {
      name: 'Small Meeting Room B',
      type: 'smallMeetingRoom',
      capacity: 6,
      pricePerDay: 420,
      imageUrl: '/images/workspaces/workspace-small-meeting-room-b.png',
      description: 'A practical meeting room for small presentations and focused team discussions.',
      equipment: ['projector'],
      isActive: true,
    },
    {
      name: 'Large Meeting Room A',
      type: 'largeMeetingRoom',
      capacity: 12,
      pricePerDay: 750,
      imageUrl: '/images/workspaces/workspace-large-meeting-room.png',
      description: 'A larger meeting room for workshops, presentations, and team sessions.',
      equipment: ['largeTv', 'projector'],
      isActive: true,
    },
    {
      name: 'Managed Suite A',
      type: 'managedSuite',
      capacity: 25,
      pricePerDay: 1600,
      imageUrl: '/images/workspaces/workspace-managed-suite.png',
      description: 'A private suite for a larger team, combining work areas and meeting space.',
      equipment: ['largeTv', 'projector'],
      isActive: true,
    },
  ],
};

const createFutureDate = (daysFromToday) => {
  const date = new Date();
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() + daysFromToday);
  return date;
};

export const createSeedReservations = () => [
  {
    userEmail: 'user1@worknest.demo',
    branchName: 'WorkNest Tel Aviv',
    workspaceName: 'Small Meeting Room A',
    startDate: createFutureDate(14),
    endDate: createFutureDate(16),
    status: 'confirmed',
  },
  {
    userEmail: 'user2@worknest.demo',
    branchName: 'WorkNest Herzliya',
    workspaceName: 'Office A',
    startDate: createFutureDate(21),
    endDate: createFutureDate(23),
    status: 'confirmed',
  },
  {
    userEmail: 'user1@worknest.demo',
    branchName: 'WorkNest Jerusalem',
    workspaceName: 'Large Meeting Room A',
    startDate: createFutureDate(28),
    endDate: createFutureDate(30),
    status: 'cancelled',
  },
];
